package com.springmvc.HYBuy.entity;

public class Users {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.uname
     *
     * @mbggenerated
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.uroleid
     *
     * @mbggenerated
     */
    private Integer uroleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.ufname
     *
     * @mbggenerated
     */
    private String ufname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.upwd
     *
     * @mbggenerated
     */
    private String upwd;

    public Users(){

    }

    public Users(String uname, Integer uroleid, String ufname, String upwd) {
        this.uid = uid;
        this.uname = uname;
        this.uroleid = uroleid;
        this.ufname = ufname;
        this.upwd = upwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.uid
     *
     * @return the value of users.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.uid
     *
     * @param uid the value for users.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.uname
     *
     * @return the value of users.uname
     *
     * @mbggenerated
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.uname
     *
     * @param uname the value for users.uname
     *
     * @mbggenerated
     */
    public void setUname(String uname) {
        this.uname = uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.uroleid
     *
     * @return the value of users.uroleid
     *
     * @mbggenerated
     */
    public Integer getUroleid() {
        return uroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.uroleid
     *
     * @param uroleid the value for users.uroleid
     *
     * @mbggenerated
     */
    public void setUroleid(Integer uroleid) {
        this.uroleid = uroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.ufname
     *
     * @return the value of users.ufname
     *
     * @mbggenerated
     */
    public String getUfname() {
        return ufname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.ufname
     *
     * @param ufname the value for users.ufname
     *
     * @mbggenerated
     */
    public void setUfname(String ufname) {
        this.ufname = ufname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.upwd
     *
     * @return the value of users.upwd
     *
     * @mbggenerated
     */
    public String getUpwd() {
        return upwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.upwd
     *
     * @param upwd the value for users.upwd
     *
     * @mbggenerated
     */
    public void setUpwd(String upwd) {
        this.upwd = upwd;
    }
}